{"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/none","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/pending","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/error(_:)"],"title":"Nil answer cases","anchor":"Nil-answer-cases"}],"abstract":[{"type":"text","text":"The network could not deliver a result (perhaps due to connectivity problems or a service outage)"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"failed","kind":"identifier"}],"platforms":["macOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/app.soulver.core\/documentation\/SoulverCore","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/failed"},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failed"}],"externalID":"s:11SoulverCore16EvaluationResultO6failedyA2CmF","symbolKind":"case","roleHeading":"Case","title":"EvaluationResult.failed","modules":[{"name":"SoulverCore"}],"role":"symbol"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/soulvercore\/evaluationresult\/failed"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://app.soulver.core/documentation/SoulverCore":{"role":"collection","kind":"symbol","title":"SoulverCore","abstract":[{"text":"A powerful natural language calculation engine","type":"text"}],"type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore","url":"\/documentation\/soulvercore"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/failed":{"kind":"symbol","role":"symbol","title":"EvaluationResult.failed","url":"\/documentation\/soulvercore\/evaluationresult\/failed","abstract":[{"text":"The network could not deliver a result (perhaps due to connectivity problems or a service outage)","type":"text"}],"type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/failed","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failed","kind":"identifier"}]},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult":{"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EvaluationResult"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult","title":"EvaluationResult","url":"\/documentation\/soulvercore\/evaluationresult","type":"topic","abstract":[{"type":"text","text":"Represents the underlying data of a result of a SoulverCore calculation"}],"navigatorTitle":[{"text":"EvaluationResult","kind":"identifier"}]},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/pending":{"kind":"symbol","role":"symbol","title":"EvaluationResult.pending","url":"\/documentation\/soulvercore\/evaluationresult\/pending","abstract":[{"type":"text","text":"A result that must be fetched asyncronously (probably over a network)"}],"type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/pending","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pending","kind":"identifier"}]},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/none":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}],"type":"topic","url":"\/documentation\/soulvercore\/evaluationresult\/none","title":"EvaluationResult.none","kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/none","abstract":[{"type":"text","text":"A null result"}],"role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/error(_:)":{"kind":"symbol","role":"symbol","title":"EvaluationResult.error(_:)","url":"\/documentation\/soulvercore\/evaluationresult\/error(_:)","abstract":[],"type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/error(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":"(","kind":"text"},{"text":"EvaluationError","preciseIdentifier":"s:11SoulverCore15EvaluationErrorO","kind":"typeIdentifier"},{"kind":"text","text":")"}]}}}