{"seeAlsoSections":[{"identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/none","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/pending","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/error(_:)"],"anchor":"Nil-answer-cases","generated":true,"title":"Nil answer cases"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"SoulverCore"}],"symbolKind":"case","externalID":"s:11SoulverCore16EvaluationResultO6failedyA2CmF","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"failed","kind":"identifier"}],"title":"EvaluationResult.failed","roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/app.soulver.core\/documentation\/SoulverCore","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult"]]},"sections":[],"identifier":{"url":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/failed","interfaceLanguage":"swift"},"abstract":[{"text":"The network could not deliver a result (perhaps due to connectivity problems or a service outage)","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/soulvercore\/evaluationresult\/failed"]}],"references":{"doc://app.soulver.core/documentation/SoulverCore":{"title":"SoulverCore","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore","role":"collection","abstract":[{"text":"A powerful natural language calculation engine","type":"text"}],"type":"topic","url":"\/documentation\/soulvercore","kind":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/failed":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"failed","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/failed","title":"EvaluationResult.failed","role":"symbol","abstract":[{"type":"text","text":"The network could not deliver a result (perhaps due to connectivity problems or a service outage)"}],"type":"topic","url":"\/documentation\/soulvercore\/evaluationresult\/failed"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult":{"kind":"symbol","navigatorTitle":[{"text":"EvaluationResult","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/soulvercore\/evaluationresult","abstract":[{"type":"text","text":"Represents the underlying data of a result of a SoulverCore calculation"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EvaluationResult","kind":"identifier"}],"title":"EvaluationResult"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/none":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/none","title":"EvaluationResult.none","role":"symbol","abstract":[{"type":"text","text":"A null result"}],"type":"topic","url":"\/documentation\/soulvercore\/evaluationresult\/none"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/pending":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/pending","kind":"symbol","title":"EvaluationResult.pending","url":"\/documentation\/soulvercore\/evaluationresult\/pending","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"pending","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"A result that must be fetched asyncronously (probably over a network)"}]},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/error(_:)":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/error(_:)","kind":"symbol","title":"EvaluationResult.error(_:)","url":"\/documentation\/soulvercore\/evaluationresult\/error(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"EvaluationError","preciseIdentifier":"s:11SoulverCore15EvaluationErrorO"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","abstract":[]}}}